### ISSUE TITLE
Move Crypto Impls to Standalone Crate

### ISSUE THREAD

**Issue by nixpulvis** [dhardy/rand#37]
To help reduce the surface area of the `rand` crate in the STD lib I would personally propose that we support a minimal set of "non-crypto" random functions in `rand`, and then create a new crate which uses the `rand` traits to extend to cryptographically secure implementations.

Sorry if this has already been proposed.

**Comment by pitdicker** [comment]
I am not sure what you mean. Can you say a bit more about which functions you mean?

**Comment by nixpulvis** [comment]
I guess what I'm saying is that it might make things a lot clearer if `rand` only had one PRNG, and OS integration, but made it easy (as it does) to extend to more. Keeping security related issues tied to a library aimed for the purpose seems like a good idea. My understanding is that PRNGs like ISAAC *could* be used for real world cryptography.

The core `rand` library could then be a bit smaller, which in addition to the benefits above, would be nice.

**Comment by dhardy** [comment]
I don't personally think there's much point in that.

There shouldn't be a *lot* of PRNGs in the `rand` crate, but there needs to be whatever is used for `thread_rng` (currently ISAAC, 32 or 64 bit), and for convenience and quality/review IMO here should be a high quality CSPRNG (ChaCha) and maybe also a small-fast PRNG (currently Xorshift, but likely that will be replaced).

I'm less sure about keeping the small-fast PRNG actually, in part because this is more likely to get replaced in the future.
